version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: go mod tidy
      - run:
          name: Run tests
          command: go test -v ./...

workflows:
  version: 2
  build:
    jobs:
      - build